hoodie.metadata.enable=true
hoodie.datasource.write.table.type=MERGE_ON_READ
hoodie.datasource.write.partitionpath.field=partitionpath
hoodie.compact.inline=false
hoodie.write.lock.provider=org.apache.hudi.client.transaction.lock.InProcessLockProvider
hoodie.datasource.write.payload.class=org.apache.hudi.common.model.OverwriteNonDefaultsWithLatestAvroPayload
hoodie.clustering.inline.max.commits=3
hoodie.clustering.inline=true
hoodie.metadata.record.index.enable=true
hoodie.metadata.record.index.min.filegroup.count=1
hoodie.metadata.record.index.max.filegroup.count=1
hoodie.index.type=RECORD_INDEX
