hoodie.metadata.enable=true
hoodie.datasource.write.table.type=MERGE_ON_READ
hoodie.compact.inline=true
hoodie.write.lock.provider=org.apache.hudi.client.transaction.lock.InProcessLockProvider
hoodie.datasource.write.payload.class=org.apache.hudi.common.model.DefaultHoodieRecordPayload
hoodie.clustering.inline.max.commits=3
hoodie.clustering.inline=true