#Updated at 2025-09-18T03:47:28.185Z
#Wed Sep 17 20:47:28 PDT 2025
hoodie.table.timeline.timezone=LOCAL
hoodie.table.version=9
hoodie.table.index.defs.path=.hoodie/.index_defs/index.json
hoodie.table.initial.version=8
hoodie.datasource.write.hive_style_partitioning=true
hoodie.table.partial.update.mode=IGNORE_DEFAULTS
hoodie.table.legacy.payload.class=org.apache.hudi.common.model.OverwriteNonDefaultsWithLatestAvroPayload
hoodie.table.metadata.partitions.inflight=
hoodie.table.checksum=4254126532
hoodie.table.keygenerator.type=SIMPLE
hoodie.partition.metafile.use.base.format=false
hoodie.table.cdc.enabled=false
hoodie.archivelog.folder=history
hoodie.table.name=table_comp_test_1_0_2_1_1_0-SNAPSHOT_1758167114
hoodie.record.merge.strategy.id=ce9acb64-bde0-424c-9b91-f6ebba25356d
hoodie.timeline.history.path=history
hoodie.populate.meta.fields=true
hoodie.compaction.record.merger.strategy=ce9acb64-bde0-424c-9b91-f6ebba25356d
hoodie.table.type=MERGE_ON_READ
hoodie.datasource.write.partitionpath.urlencode=false
hoodie.table.base.file.format=PARQUET
hoodie.datasource.write.drop.partition.columns=false
hoodie.table.metadata.partitions=column_stats,files,partition_stats
hoodie.timeline.layout.version=2
hoodie.table.multiple.base.file.formats.enable=false
hoodie.record.merge.mode=COMMIT_TIME_ORDERING
hoodie.table.recordkey.fields=uuid
hoodie.table.partition.fields=partitionpath
hoodie.timeline.path=timeline
